sudo: false
language: python
services:
    - postgresql
python:
    - "2.7"
    - "3.4"
env:
    - DJANGO_PACKAGE="Django>=1.7,<1.8" DB=sqlite
    - DJANGO_PACKAGE="Django>=1.8,<1.9" DB=sqlite
    - DJANGO_PACKAGE="Django>=1.7,<1.8" DB=postgres
    - DJANGO_PACKAGE="Django>=1.8,<1.9" DB=postgres
install: pip install $DJANGO_PACKAGE markdown docutils
before_script: psql -c 'create database test;' -U postgres
script: ./run_tests.sh
notifications:
    email:
        - james.p.turk@gmail.com
