language: python
python:
    - "2.7"
    - "3.3"
env:
    - DJANGO_PACKAGE="Django>=1.5,<1.6"
    - DJANGO_PACKAGE="Django>=1.6,<1.7"
    - DJANGO_PACKAGE="https://www.djangoproject.com/download/1.7b1/tarball/"
install: pip install $DJANGO_PACKAGE markdown docutils --use-mirrors
script: django-admin.py test --settings=markupfield.tests.settings --pythonpath=.
notifications:
    email:
        - james.p.turk@gmail.com
